#! /usr/bin/env php
<?php

use App\Commands\ShowCommand;
use App\Commands\DownloadCommand;
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

const DEFAULT_DIR = __DIR__;
$dotenv = new Dotenv(DEFAULT_DIR);
$dotenv->load();
$app = new Application('Codecourse downloader', '1.0');
$app->add(new DownloadCommand());

$app->run();